import type { Metadata } from "next";

import './globals.css';  // これでアプリケーション全体に適用される

export const metadata: Metadata = {
    title: "Tag Todo", // タブのtitle
    description: "Generated by create next app", // メタタグに表示される文字列
};

const RootLayout = ({ children }: Readonly<{ children: React.ReactNode }>) => {
    return (
        <html lang="en">
            <body>{children}</body>
        </html>
    );
};

export default RootLayout;
